# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/671cee41-1a1f-412d-9682-a02e8a5807ee";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/179000c4-9602-4f15-930d-24c19389081e";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/671cee41-1a1f-412d-9682-a02e8a5807ee";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/671cee41-1a1f-412d-9682-a02e8a5807ee";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/671cee41-1a1f-412d-9682-a02e8a5807ee";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B975-CCF2";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { 
    device = "/dev/nvme0n1p2";
    randomEncryption.enable = true;
    } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
