# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "hp-wmi" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b71a234e-6ef0-4fe4-b592-f254aa147858";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  boot.initrd.luks.devices."nixos-root".device = "/dev/disk/by-uuid/d83c53f7-8f7b-48ad-96fc-09d825f0bd94";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b71a234e-6ef0-4fe4-b592-f254aa147858";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b71a234e-6ef0-4fe4-b592-f254aa147858";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/b71a234e-6ef0-4fe4-b592-f254aa147858";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/b71a234e-6ef0-4fe4-b592-f254aa147858";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=120" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B90-F167";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ { 
    device = "/swap/swapfile";
    size = 16*1024;
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
